import React from 'react';

const About = () => (
  <div class="text-image-wrap container" id="about">
    <img src="professional.jpg" alt="Headshot" class="wrap-image" />
    <p>Hello! I'm Darren Tran, a technology enthusiast and lifelong learner with a diverse professional background and a passion for innovation. My career journey has been unique and multidimensional, weaving through the fields of finance, customer service, and now tech. With a strong foundation in management and economics, I’ve learned to leverage my diverse experiences to excel in different environments, from large corporations to tech startups.</p>
    <p>I began my career after earning my Bachelor of Arts in Economics from the University of California, San Diego, and an Associate of Arts in Psychology from San Diego City College. My early roles included working at LPL Financial as an Operations Specialist, where I led two process improvement projects that increased departmental productivity by over 200% and 300%. This experience honed my analytical and problem-solving skills, which I further developed as an Associate Accountant at Kaiser Permanente, where I handled complex payment processes and generated management reports to streamline operations.</p>
    <p>Seeking to expand my knowledge and capabilities, I pursued a Master of Management Studies at Duke University, The Fuqua School of Business, where I learned to navigate the complexities of modern business, combining strategic thinking with a passion for innovation. These experiences motivated me to pivot into the tech industry, where I could merge my technical skills with my business acumen.</p>
    <p>My transition into tech began with an apprenticeship as an IT Support Technician, where I developed a strong foundation in server administration, user account management, and network configuration. I learned to troubleshoot hardware and software issues and provide effective on-site support, skills that are essential in today’s digital world. Following this, I worked as a Full Stack Developer at Kenai's House, collaborating with another developer to build a production-ready website. This experience allowed me to apply my knowledge of JavaScript, React, and responsive web design, and I discovered a love for creating seamless, user-friendly digital experiences.</p>
    <p>I’ve also pursued certifications to deepen my technical expertise. I'm an AWS Certified Cloud Practitioner and am currently working toward my AWS Solutions Architect Associate and CompTIA Network+ certifications. I’ve built and deployed a MERN (MySQL, Express, React, Node) stack application on a third-party server, restored an old computer into a functional local web server with a custom domain, and gained hands-on experience with tools like Docker, SharePoint, and Salesforce. I am particularly passionate about cloud computing, data management, and leveraging technology to solve complex problems.</p>
    <p>My journey has taught me the value of adaptability, continuous learning, and a growth mindset. I am dedicated to combining my technical knowledge with my background in management to help organizations innovate, improve processes, and achieve their strategic goals. I thrive in dynamic environments where I can use my skills in both tech and business to drive meaningful impact.</p>
    <p>Currently, I am seeking opportunities to bring my diverse skill set to a forward-thinking organization that values innovation and growth. I am eager to contribute to projects involving cloud computing, data management, and IT support while continuing to expand my knowledge and expertise in these areas.</p>
    <p>When I'm not immersed in the world of technology, I enjoy exploring new tools, participating in coding challenges, and sharing my knowledge through mentorship. I believe in the power of technology to transform businesses and communities, and I am excited to be a part of this journey.</p>
    <p>Let’s connect and explore how we can work together to create impactful and innovative solutions!</p>
    </div>
);

export default About;
